model:
  name: unet
  params:
    in_ch: 2             # 实际数据集应该3 此处仅为测试流程性
    out_ch: 1
    base: 32

data:
  # use_dummy: true        # 本地没有数据时 测试空转
  use_dummy: false      # 实际数据
  dummy_length: 16       # 迭代样本个数
  dummy_H: 256
  dummy_W: 384
  # batch_size: 2

  # 实际数据路径 use_dummy: false 时生效
  root_noisy: /data/shared_folder/projectionsNoisy
  root_clean: /data/shared_folder/projectionsNoisy
  ids: [0]   # 先只用一个ID调试，确认能跑
  batch_size: 4
  num_workers: 4
  truncate_left: 350
  truncate_right: 350
  normalize: percentile
  pin_memory: true

  pin_memory: true

  # # 逐角度遍历设置
  # step: 1            # 每隔一帧取一张
  # downsample: 1      # H/W 各降采样一半
  # truncate_left: 350
  # truncate_right: 350
  # mask_mode: fixed   # 数据本身非零自动掩膜，写 auto_nonzero
  # normalize: percentile
  # add_angle_channel: true   # 输入里增加 angle 归一化通道可提升收敛

train:
  device: cuda
  epochs: 10
  lr: 3e-4

  ckpt_dir: checkpoints

